import type { CsvRow } from "../types";

export function generateSampleCSV(): void {
  const residents: CsvRow[] = [
    { mcr: "M000001A", name: "Dr. Alice Johnson", resident_year: 3, career_blocks_completed: 24 },
    { mcr: "M000002A", name: "Dr. Bob Smith", resident_year: 2, career_blocks_completed: 12 },
    { mcr: "M000003A", name: "Dr. Carol Lee", resident_year: 1, career_blocks_completed: 0 },
  ];

  const residentHistory: CsvRow[] = [
    {
      mcr: "M000001A",
      year: 1,
      month_block: 1,
      career_block: 1,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 2,
      career_block: 2,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 3,
      career_block: 3,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 4,
      career_block: 4,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 5,
      career_block: 5,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 6,
      career_block: 6,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 7,
      career_block: 7,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 8,
      career_block: 8,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 9,
      career_block: 9,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 10,
      career_block: 10,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 11,
      career_block: 11,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 1,
      month_block: 12,
      career_block: 12,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 1,
      career_block: 13,
      posting_code: "GM (KTPH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 2,
      career_block: 14,
      posting_code: "GM (KTPH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 3,
      career_block: 15,
      posting_code: "GM (KTPH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 4,
      career_block: 16,
      posting_code: "NL (NNI)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 5,
      career_block: 17,
      posting_code: "NL (NNI)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 6,
      career_block: 18,
      posting_code: "NL (NNI)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 7,
      career_block: 19,
      posting_code: "ED (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 8,
      career_block: 20,
      posting_code: "ED (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 9,
      career_block: 21,
      posting_code: "ED (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 10,
      career_block: 22,
      posting_code: "GRM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 11,
      career_block: 23,
      posting_code: "GRM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 2,
      month_block: 12,
      career_block: 24,
      posting_code: "GRM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 1,
      career_block: 25,
      posting_code: "Renal (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 2,
      career_block: 26,
      posting_code: "Renal (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 3,
      career_block: 27,
      posting_code: "Renal (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 4,
      career_block: 28,
      posting_code: "Endocrine (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 5,
      career_block: 29,
      posting_code: "Endocrine (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 6,
      career_block: 30,
      posting_code: "",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 7,
      career_block: 31,
      posting_code: "Gastro (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 8,
      career_block: 32,
      posting_code: "Gastro (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 9,
      career_block: 33,
      posting_code: "Gastro (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 10,
      career_block: 34,
      posting_code: "MedComm (Comm)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 11,
      career_block: 35,
      posting_code: "MedComm (Comm)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000001A",
      year: 3,
      month_block: 12,
      career_block: 36,
      posting_code: "MedComm (Comm)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 1,
      career_block: 1,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 2,
      career_block: 2,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 3,
      career_block: 3,
      posting_code: "GM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 4,
      career_block: 4,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 5,
      career_block: 5,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 6,
      career_block: 6,
      posting_code: "CVM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 7,
      career_block: 7,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 8,
      career_block: 8,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 9,
      career_block: 9,
      posting_code: "MICU (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 10,
      career_block: 10,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 11,
      career_block: 11,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 1,
      month_block: 12,
      career_block: 12,
      posting_code: "RCCM (TTSH)",
      is_current_year: 0,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 1,
      career_block: 13,
      posting_code: "Haemato (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 2,
      career_block: 14,
      posting_code: "Haemato (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 3,
      career_block: 15,
      posting_code: "",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 4,
      career_block: 16,
      posting_code: "ID (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 5,
      career_block: 17,
      posting_code: "ID (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 6,
      career_block: 18,
      posting_code: "ID (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 7,
      career_block: 19,
      posting_code: "Med Onco (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 8,
      career_block: 20,
      posting_code: "Med Onco (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 9,
      career_block: 21,
      posting_code: "Med Onco (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 10,
      career_block: 22,
      posting_code: "RAI (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 11,
      career_block: 23,
      posting_code: "RAI (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000002A",
      year: 2,
      month_block: 12,
      career_block: 24,
      posting_code: "RAI (TTSH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 1,
      career_block: 1,
      posting_code: "GM (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 2,
      career_block: 2,
      posting_code: "GM (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 3,
      career_block: 3,
      posting_code: "GM (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 4,
      career_block: 4,
      posting_code: "Renal (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 5,
      career_block: 5,
      posting_code: "Renal (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 6,
      career_block: 6,
      posting_code: "Renal (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 7,
      career_block: 7,
      posting_code: "Endocrine (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 8,
      career_block: 8,
      posting_code: "",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 9,
      career_block: 9,
      posting_code: "Endocrine (KTPH)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 10,
      career_block: 10,
      posting_code: "Derm (NSC)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 11,
      career_block: 11,
      posting_code: "Derm (NSC)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
    {
      mcr: "M000003A",
      year: 1,
      month_block: 12,
      career_block: 12,
      posting_code: "Derm (NSC)",
      is_current_year: 1,
      is_leave: 0,
      leave_type: "",
    },
  ];

  const residentPreferences: CsvRow[] = [
    { mcr: "M000001A", preference_rank: 1, posting_code: "Renal (TTSH)" },
    { mcr: "M000001A", preference_rank: 2, posting_code: "Endocrine (TTSH)" },
    { mcr: "M000001A", preference_rank: 3, posting_code: "Gastro (TTSH)" },
    { mcr: "M000001A", preference_rank: 4, posting_code: "MedComm (Comm)" },
    { mcr: "M000001A", preference_rank: 5, posting_code: "PMD (TTSH)" },
    { mcr: "M000002A", preference_rank: 1, posting_code: "Haemato (TTSH)" },
    { mcr: "M000002A", preference_rank: 2, posting_code: "ID (TTSH)" },
    { mcr: "M000002A", preference_rank: 3, posting_code: "Med Onco (TTSH)" },
    { mcr: "M000002A", preference_rank: 4, posting_code: "RAI (TTSH)" },
    { mcr: "M000002A", preference_rank: 5, posting_code: "Rehab (TTSH)" },
    { mcr: "M000003A", preference_rank: 1, posting_code: "Derm (NSC)" },
    { mcr: "M000003A", preference_rank: 2, posting_code: "Endocrine (KTPH)" },
    { mcr: "M000003A", preference_rank: 3, posting_code: "Renal (KTPH)" },
    { mcr: "M000003A", preference_rank: 4, posting_code: "Med Onco (NCC)" },
    { mcr: "M000003A", preference_rank: 5, posting_code: "PMD (TTSH)" },
  ];

  const residentSrPreferences: CsvRow[] = [
    { mcr: "M000001A", preference_rank: 1, base_posting: "Renal" },
    { mcr: "M000001A", preference_rank: 2, base_posting: "Endocrine" },
    { mcr: "M000001A", preference_rank: 3, base_posting: "Gastro" },
    { mcr: "M000002A", preference_rank: 1, base_posting: "Haemato" },
    { mcr: "M000002A", preference_rank: 2, base_posting: "ID" },
    { mcr: "M000002A", preference_rank: 3, base_posting: "Med Onco" },
    { mcr: "M000003A", preference_rank: 1, base_posting: "Derm" },
    { mcr: "M000003A", preference_rank: 2, base_posting: "Endocrine" },
    { mcr: "M000003A", preference_rank: 3, base_posting: "Renal" },
  ];

  const postings: CsvRow[] = [
    {
      posting_code: "CVM (TTSH)",
      posting_name: "Cardiovascular Medicine (TTSH)",
      posting_type: "core",
      max_residents: 3,
      required_block_duration: 3,
    },
    {
      posting_code: "ED (TTSH)",
      posting_name: "Emergency Department (TTSH)",
      posting_type: "core",
      max_residents: 4,
      required_block_duration: 1,
    },
    {
      posting_code: "Endocrine (TTSH)",
      posting_name: "Endocrinology (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "Gastro (TTSH)",
      posting_name: "Gastroenterology (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "GM (TTSH)",
      posting_name: "General Medicine (TTSH)",
      posting_type: "core",
      max_residents: 5,
      required_block_duration: 3,
    },
    {
      posting_code: "GRM (TTSH)",
      posting_name: "Geriatric Medicine (TTSH)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 2,
    },
    {
      posting_code: "MedComm (Comm)",
      posting_name: "Medical Community (Comm)",
      posting_type: "elective",
      max_residents: 1,
      required_block_duration: 1,
    },
    {
      posting_code: "Haemato (TTSH)",
      posting_name: "Haematology (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "ID (TTSH)",
      posting_name: "Infectious Diseases (TTSH)",
      posting_type: "elective",
      max_residents: 3,
      required_block_duration: 3,
    },
    {
      posting_code: "Med Onco (TTSH)",
      posting_name: "Medical Oncology (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "PMD (TTSH)",
      posting_name: "Palliative Medicine (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "RAI (TTSH)",
      posting_name: "Rheumatology and Immunology (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "RCCM (TTSH)",
      posting_name: "Respiratory Critical Care Medicine (TTSH)",
      posting_type: "core",
      max_residents: 3,
      required_block_duration: 2,
    },
    {
      posting_code: "MICU (TTSH)",
      posting_name: "Medical ICU (TTSH)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 1,
    },
    {
      posting_code: "Rehab (TTSH)",
      posting_name: "Rehabilitation (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "Renal (TTSH)",
      posting_name: "Renal Medicine (TTSH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "CVM (KTPH)",
      posting_name: "Cardiovascular Medicine (KTPH)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "Endocrine (KTPH)",
      posting_name: "Endocrinology (KTPH)",
      posting_type: "elective",
      max_residents: 1,
      required_block_duration: 3,
    },
    {
      posting_code: "GM (KTPH)",
      posting_name: "General Medicine (KTPH)",
      posting_type: "core",
      max_residents: 3,
      required_block_duration: 3,
    },
    {
      posting_code: "GRM (KTPH)",
      posting_name: "Geriatric Medicine (KTPH)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 2,
    },
    {
      posting_code: "MICU (KTPH)",
      posting_name: "Medical ICU (KTPH)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 1,
    },
    {
      posting_code: "RCCM (KTPH)",
      posting_name: "Respiratory Critical Care Medicine (KTPH)",
      posting_type: "core",
      max_residents: 1,
      required_block_duration: 2,
    },
    {
      posting_code: "Renal (KTPH)",
      posting_name: "Renal Medicine (KTPH)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "Med Onco (NCC)",
      posting_name: "Medical Oncology (NCC)",
      posting_type: "elective",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "NL (NNI)",
      posting_name: "Neurology (NNI)",
      posting_type: "core",
      max_residents: 2,
      required_block_duration: 3,
    },
    {
      posting_code: "Derm (NSC)",
      posting_name: "Dermatology (NSC)",
      posting_type: "elective",
      max_residents: 1,
      required_block_duration: 3,
    },
    {
      posting_code: "GM (NUH)",
      posting_name: "General Medicine (NUH)",
      posting_type: "CCR",
      max_residents: 2,
      required_block_duration: 1,
    },
    {
      posting_code: "GM (SGH)",
      posting_name: "General Medicine (SGH)",
      posting_type: "CCR",
      max_residents: 2,
      required_block_duration: 1,
    },
    {
      posting_code: "GM (CGH)",
      posting_name: "General Medicine (CGH)",
      posting_type: "CCR",
      max_residents: 1,
      required_block_duration: 1,
    },
    {
      posting_code: "GM (SKH)",
      posting_name: "General Medicine (SKH)",
      posting_type: "CCR",
      max_residents: 2,
      required_block_duration: 1,
    },
    {
      posting_code: "GM (WH)",
      posting_name: "General Medicine (WH)",
      posting_type: "CCR",
      max_residents: 3,
      required_block_duration: 3,
    },
  ];

  const residentLeaves: CsvRow[] = [
    { mcr: "M000002A", month_block: 1, leave_type: "LOA", posting_code: "" },
    { mcr: "M000002A", month_block: 2, leave_type: "LOA", posting_code: "" },
    { mcr: "M000002A", month_block: 3, leave_type: "LOA", posting_code: "" },
    { mcr: "M000003A", month_block: 8, leave_type: "LOA", posting_code: "" },
    { mcr: "M000003A", month_block: 9, leave_type: "LOA", posting_code: "" },
  ];

  // convert object arrays to CSV string
  const toCsv = (data: CsvRow[]): string => {
    if (data.length === 0) return "";
    const headers = Object.keys(data[0]);
    const rows = data.map((row) =>
      headers.map((header) => String(row[header] ?? "")).join(",")
    );
    return [headers.join(","), ...rows].join("\n");
  };

  const files = [
    { filename: "sample_residents.csv", content: toCsv(residents) },
    {
      filename: "sample_resident_history.csv",
      content: toCsv(residentHistory),
    },
    {
      filename: "sample_resident_preferences.csv",
      content: toCsv(residentPreferences),
    },
    {
      filename: "sample_resident_sr_preferences.csv",
      content: toCsv(residentSrPreferences),
    },
    { filename: "sample_postings.csv", content: toCsv(postings) },
    { filename: "sample_resident_leaves.csv", content: toCsv(residentLeaves) },
  ];

  // trigger downloads
  files.forEach(({ filename, content }) => {
    const blob = new Blob([content], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  });
}
